# Measurements all in meters
SINGLES_LINE_WIDTH = 5.18
DOUBLES_LINE_WIDTH = 6.10
ALLEY_WIDTH = 0.46
DOUBLES_SERVICE_LINE_WIDTH = 0.76
SERVICE_COURT_WIDTH = 3.91
SERVICE_LINE_WIDTH = 1.98
LINE_WIDTH = 0.004

# lin dan height
PLAYER_1_HEIGHT_METERS = 1.78
# lee chong wei height
PLAYER_2_HEIGHT_METERS = 1.72